export const GET_ADMIN_ALL_ARTICLE = 'GET_ADMIN_ALL_ARTICLE';
export const GET_ADMIN_ONE_ARTICLE = 'GET_ADMIN_ONE_ARTICLE';
export const ADMIN_CREATE_NEW_ARTICLE = 'ADMIN_CREATE_NEW_ARTICLE';
export const ADMIN_UPDATE_ONE_ARTICLE = 'ADMIN_UPDATE_ONE_ARTICLE';
export const ADMIN_DELETE_ONE_ARTICLE = 'ADMIN_DELETE_ONE_ARTICLE';
