export const GET_ADMIN_ALL_ARTICLE = 'GET_ADMIN_ALL_ARTICLE';
export const GET_ADMIN_ONE_ARTICLE = 'GET_ADMIN_ONE_ARTICLE';
export const ADMIN_CREATE_NEW_ARTICLE = 'ADMIN_CREATE_NEW_ARTICLE';
export const ADMIN_UPDATE_ONE_ARTICLE = 'ADMIN_UPDATE_ONE_ARTICLE';
export const ADMIN_DELETE_ONE_ARTICLE = 'ADMIN_DELETE_ONE_ARTICLE';

export const GET_ADMIN_ALL_COURSE = 'GET_ADMIN_ALL_COURSE';
export const GET_ADMIN_ONE_COURSE = 'GET_ADMIN_ONE_COURSE';
export const ADMIN_CREATE_NEW_COURSE = 'ADMIN_CREATE_NEW_COURSE';
export const ADMIN_UPDATE_ONE_COURSE = 'ADMIN_UPDATE_ONE_COURSE';
export const ADMIN_DELETE_ONE_COURSE = 'ADMIN_DELETE_ONE_COURSE';

export const GET_ADMIN_ALL_JOB = 'GET_ADMIN_ALL_JOB';
export const GET_ADMIN_ONE_JOB = 'GET_ADMIN_ONE_JOB';
export const ADMIN_CREATE_NEW_JOB = 'ADMIN_CREATE_NEW_JOB';
export const ADMIN_UPDATE_ONE_JOB = 'ADMIN_UPDATE_ONE_JOB';
export const ADMIN_DELETE_ONE_JOB = 'ADMIN_DELETE_ONE_JOB';

export const GET_ADMIN_ALL_USER = 'GET_ADMIN_ALL_USER';
export const GET_ADMIN_ONE_USER = 'GET_ADMIN_ONE_USER';
export const ADMIN_CREATE_NEW_USER = 'ADMIN_CREATE_NEW_USER';
export const ADMIN_UPDATE_ONE_USER = 'ADMIN_UPDATE_ONE_USER';
export const ADMIN_DELETE_ONE_USER = 'ADMIN_DELETE_ONE_USER';

export const GET_ADMIN_ALL_CERTIFCATE = 'GET_ADMIN_ALL_CERTIFCATE';
export const GET_ADMIN_ONE_CERTIFCATE = 'GET_ADMIN_ONE_CERTIFCATE';
export const ADMIN_CREATE_NEW_CERTIFCATE = 'ADMIN_CREATE_NEW_CERTIFCATE';
export const ADMIN_UPDATE_ONE_CERTIFCATE = 'ADMIN_UPDATE_ONE_CERTIFCATE';
export const ADMIN_DELETE_ONE_CERTIFCATE = 'ADMIN_DELETE_ONE_CERTIFCATE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_SINGUP = 'USER_SINGUP';

export const GET_USER_ALL_ARTICLE = 'GET_USER_ALL_ARTICLE';
export const GET_USER_ONE_ARTICLE = 'GET_USER_ONE_ARTICLE';

export const GET_USER_ALL_COURSE = 'GET_USER_ALL_COURSE';
export const GET_USER_ONE_COURSE = 'GET_USER_ONE_COURSE';

export const GET_USER_ALL_JOB = 'GET_USER_ALL_JOB';
export const GET_USER_ONE_JOB = 'GET_USER_ONE_JOB';

export const USER_EDIT_PROFILE = 'USER_EDIT_PROFILE';

export const CREATE_NEW_EXAM = 'CREATE_NEW_EXAM';
export const UPDATE_NEW_EXAM = 'UPDATE_NEW_EXAM';
export const GET_ALL_EXAM = 'GET_ALL_EXAM';
export const GET_ONE_EXAM = 'GET_ONE_EXAM';
export const DELETE_ONE_EXAM = 'DELETE_ONE_EXAM';
